### ISSUE TITLE
Better Setup Instruction in README

### ISSUE THREAD

**Issue by arv-anshul** [m1guer/basedpyright-zed#6]
I am configuring my Zed with this extension but getting too many problems like how to sync with my current project's virtual environment (which I figured out from **Issue #3**).

Even after that I'm struggling to change the default behaviour of `basedpyright`'s `typeCheckingMode` to `standard` (by-default behaviour is `strict`).

BTW, currently I've configured my `pyproject.toml` to change the `typeCheckingMode`, which is not what I want instead I want to configure this setting in Zed's `settings.json` file which allow me to work with projects without creating `pyproject.toml` file.

```toml
[tool.basedpyright]
typeCheckingMode = "standard"
```

<details>
<summary>my current lsp config for `basedpyright`</summary>

```jsonc
"lsp": {
  "basedpyright": {
    "settings": {
      // TODO: include "typeCheckingMode" option here instead of pyproject.toml file
      // "analysis": { "typeCheckingMode": "off" },  // this doesn't works (i've tried from docs)
      "python": {
        "pythonPath": ".venv/bin/python"
      }
    }
  }
}
```

</details>

> [!IMPORTANT]
>
> Please add some instruction regarding these configurations for `settings.json` in **README.md**.
> Also, add related docs for more info.

❤️ Thanks for the extension!

**Comment by m1guer** [comment]
working on.

**Comment by HamzaFarhan** [comment]
Any update on this?

**Comment by m1guer** [comment]
sorry, iam out of time.

**Comment by HamzaFarhan** [comment]
That's fine. Do we know what should be in our pyproject.toml and what should be in our settings.json?

**Comment by skewty** [comment]
@arv-anshul it is important to note that according to [the official basedpyright docs](https://docs.basedpyright.com/latest/configuration/config-files/) the `[tool.pyright]` section in `pyproject.toml` is also supported by basedpyright for backwards compatibility.

That said, does this extension support the same when it comes to Zed's `settings.json` file (will it read settings from `lsp.basedpyright` and fallback to `lsp.pyright`?  I don't believe this is made clear in the `README.md` file.

Also, which basedpyright is used by this extension?  The one in my system path or the one in the project virtualenv?  Does one take precedence over the other? I don't believe this is made clear in the `README.md` file.

**Comment by JaagupAverin** [comment]
After debugging this I figured out that the correct snippet is:
```json
{
  "lsp": {
    "basedpyright": {
      "settings": {
        "python": {
          "pythonPath": ".venv/bin/python"
        },
        "basedpyright.analysis": {
          "diagnosticMode": "workspace",
          "inlayHints": {
            "callArgumentNames": false
          }
        }
      }
    }
  }
}
```
